name: Deploy Laravel to FTP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, xml, ctype, json, tokenizer, pdo_mysql, gd
        coverage: none

    - name: Install Composer dependencies
      run: |
        composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

    - name: Install npm dependencies
      run: |
        npm ci --prefer-offline --no-audit

    - name: Build assets
      run: |
        npm run build

    - name: Create deployment package
      run: |
        # Remove files that shouldn't be deployed
        rm -rf node_modules/
        rm -rf tests/
        rm -f .env.example
        rm -f phpunit.xml
        rm -f package.json
        rm -f package-lock.json
        rm -f webpack.mix.js
        rm -f composer.json
        rm -f composer.lock
        
        # Create necessary directories
        mkdir -p storage/framework/{sessions,views,cache}
        mkdir -p storage/logs
        mkdir -p bootstrap/cache

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_PATH }}
        local-dir: ./
        exclude: |
          **/.git*
          **/.github*
          **/node_modules/**
          **/tests/**
          **/.env*
          **/storage/**
          **/bootstrap/cache/**
        dangerous-clean-slate: true
