name: Deploy Laravel to FTP

on:
  push:
    branches:
      - main   # only deploy when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_PATH }}
name: Deploy Laravel to FTP

on:
  push:
    branches: [ main ]   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout Repo
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Setup PHP (Composer এর জন্য)
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, xml, ctype, json, tokenizer, pdo_mysql, gd
        coverage: none

    # 3. Install Composer dependencies (production only)
    - name: Install Composer dependencies
      run: |
        composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

    # 4. Install npm dependencies & Build Assets (vite/webpack)
    - name: Install npm dependencies
      run: npm ci --prefer-offline --no-audit

    - name: Build assets
      run: npm run build

    # 5. Clean up unnecessary files before deploy
    - name: Cleanup before deploy
      run: |
        rm -rf node_modules/
        rm -rf tests/
        rm -f .env.example
        rm -f phpunit.xml
        rm -f webpack.mix.js  # remove only if not using Mix

    # 6. Deploy to FTP
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_PATH }}
        local-dir: ./ 
        exclude: |
          **/.git*
          **/.github*
          **/node_modules/**
          **/tests/**
          **/.env*
        dangerous-clean-slate: true
